image: php:8.0
before_script:
    - apt-get update -qq
    - apt-get install -y -qq git
    - git add composer.lock composer.json
    - git commit -m "add composer lock"
    - gem install dpl
phpunit tests:
  stage: test
  script:
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.example .env
    - vendor/bin/phpunit tests
deploy staged:
  type: deploy
  stage: satging
  script:
    - apt-get install -y ruby
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
    - php artisan key:generate
    - php artisan migrate
  only:
    - staging
deploy prduction:
  type:deploy
  stage: production
  script:
    - apt-get install -y ruby
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
    - php artisan key:generate
    - php artisan migrate
  only:
    - staging
